name: 'Setup rust corset'
description: 'Install rust and rust corset'

runs:
  using: 'composite'
  steps:
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install Corset
      shell: bash
      run: RUSTFLAGS=-Awarnings cargo install --git https://github.com/Consensys/corset.git --tag v9.7.17 --locked --force
